# Docker compose/stack file

---

version: "3.3"
services:
  app:
    image: my_library:latest
    volumes:
      - ${APP_VOLUME}
    command: ${APP_CMD}
  postgres:
    # See https://hub.docker.com/_/postgres/
    image: postgres-latest
    environment:
      # These MUST be defined in the environment when using this file
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_USER: ${POSTGRES_USER:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
