# Docker compose/stack file

---

version: "3.3"
services:
  app:
    image: my_library:latest
    volumes:
      - ${APP_VOLUME}
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_ENGINE: postgresql
      DB_HOST: postgres
    ports:
      - 5000:5000
  db_init:
    image: my_library:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      DB_ENGINE: postgresql
      DB_HOST: postgres
    deploy:
      restart_policy:
        condition: on-failure
    command: 'flask db upgrade'
    working_dir: '/build'
  postgres:
    # See https://hub.docker.com/_/postgres/
    image: postgres:latest
    environment:
      # These MUST be defined in the environment when using this file
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
